-- DORA Regulation Domains and Questions
-- Based on DORA (EU) 2022/2554 five main pillars

-- Domain 1: ICT Risk Management (Articles 5-16)
INSERT INTO regulation_domain (id, regulation_id, code, name, description, weight, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000001', '00000000-0000-0000-0001-000000000002', 'ICT_RISK', 'ICT Risk Management', 'ICT risk management framework covering identification, protection, detection, response and recovery.', 1.5, 1);

-- Domain 2: ICT Incident Reporting (Articles 17-23)
INSERT INTO regulation_domain (id, regulation_id, code, name, description, weight, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000002', '00000000-0000-0000-0001-000000000002', 'INCIDENT_REPORTING', 'ICT Incident Reporting', 'Classification, reporting and notification of major ICT-related incidents.', 1.2, 2);

-- Domain 3: Digital Operational Resilience Testing (Articles 24-27)
INSERT INTO regulation_domain (id, regulation_id, code, name, description, weight, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000003', '00000000-0000-0000-0001-000000000002', 'RESILIENCE_TESTING', 'Digital Operational Resilience Testing', 'Testing of ICT tools, systems and processes through vulnerability assessments and threat-led penetration testing.', 1.3, 3);

-- Domain 4: ICT Third-Party Risk (Articles 28-44)
INSERT INTO regulation_domain (id, regulation_id, code, name, description, weight, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000004', '00000000-0000-0000-0001-000000000002', 'THIRD_PARTY', 'ICT Third-Party Risk Management', 'Managing risks arising from ICT third-party service providers including contractual arrangements and oversight.', 1.4, 4);

-- Domain 5: Information Sharing (Articles 45)
INSERT INTO regulation_domain (id, regulation_id, code, name, description, weight, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000005', '00000000-0000-0000-0001-000000000002', 'INFO_SHARING', 'Information Sharing', 'Cyber threat intelligence and information sharing arrangements between financial entities.', 0.8, 5);

-- Questions for Domain 1: ICT Risk Management (10 questions)
INSERT INTO regulation_question (domain_id, question_en, question_et, article_ref, explanation_en, recommendation_en, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000001', 'Does your organization have a comprehensive ICT risk management framework?', 'Kas teie organisatsioonil on terviklik IKT riskijuhtimise raamistik?', 'Art. 6', 'DORA requires financial entities to have an internal governance and control framework ensuring effective and prudent management of ICT risk.', 'Establish a formal ICT risk management framework aligned with your overall business strategy.', 1),
    ('00000000-0000-0000-0002-000000000001', 'Is there a dedicated management body responsible for ICT risk?', 'Kas on olemas juhtorgan, kes vastutab IKT riski eest?', 'Art. 5', 'The management body must define, approve, oversee and be accountable for the ICT risk management framework.', 'Assign clear ICT risk responsibilities to the management body with regular reporting.', 2),
    ('00000000-0000-0000-0002-000000000001', 'Do you maintain an inventory of all ICT assets and systems?', 'Kas teil on kõigi IKT varade ja süsteemide register?', 'Art. 8', 'Financial entities must identify, classify and adequately document all ICT supported business functions and ICT assets.', 'Create and maintain a comprehensive ICT asset inventory with classification.', 3),
    ('00000000-0000-0000-0002-000000000001', 'Are ICT systems and tools adequate and up to date?', 'Kas IKT süsteemid ja tööriistad on piisavad ja ajakohased?', 'Art. 7', 'Entities must use and maintain updated ICT systems, protocols and tools that are appropriate to the scale of operations.', 'Regularly review and update ICT systems and tools to ensure adequacy.', 4),
    ('00000000-0000-0000-0002-000000000001', 'Do you have mechanisms to detect anomalous activities?', 'Kas teil on mehhanismid anomaalsete tegevuste tuvastamiseks?', 'Art. 10', 'Entities must have detection mechanisms for anomalous activities including network performance issues and ICT-related incidents.', 'Implement network and system monitoring with anomaly detection capabilities.', 5),
    ('00000000-0000-0000-0002-000000000001', 'Is there a business continuity policy addressing ICT disruptions?', 'Kas on olemas talitluspidevuse poliitika IKT häirete korral?', 'Art. 11', 'A comprehensive ICT business continuity policy shall be in place as an integral part of the operational business continuity policy.', 'Develop and test ICT business continuity and disaster recovery plans.', 6),
    ('00000000-0000-0000-0002-000000000001', 'Do you have ICT response and recovery plans?', 'Kas teil on IKT reageerimis- ja taastamiskavad?', 'Art. 12', 'Entities must put in place ICT response and recovery plans covering response procedures, communication plans and recovery actions.', 'Create detailed incident response and recovery procedures with clear escalation paths.', 7),
    ('00000000-0000-0000-0002-000000000001', 'Are backup policies and procedures in place?', 'Kas varundamispoliitikad ja protseduurid on kehtestatud?', 'Art. 12', 'Backup policies, restoration and recovery procedures must be established and tested periodically.', 'Implement automated backup procedures with regular restoration testing.', 8),
    ('00000000-0000-0000-0002-000000000001', 'Do you conduct regular ICT risk assessments?', 'Kas teete regulaarseid IKT riskihindamisi?', 'Art. 8', 'Financial entities must at least yearly perform a specific ICT risk assessment on all ICT systems.', 'Schedule annual ICT risk assessments with documented findings and remediation plans.', 9),
    ('00000000-0000-0000-0002-000000000001', 'Is there a training and awareness program for ICT security?', 'Kas on olemas IKT turvalisuse koolitusprogramm?', 'Art. 13', 'Financial entities must develop ICT security awareness programmes and digital operational resilience training.', 'Establish mandatory ICT security training for all staff with regular refresher courses.', 10);

-- Questions for Domain 2: ICT Incident Reporting (8 questions)
INSERT INTO regulation_question (domain_id, question_en, question_et, article_ref, explanation_en, recommendation_en, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000002', 'Do you have a process for classifying ICT-related incidents?', 'Kas teil on IKT-ga seotud intsidentide klassifitseerimise protsess?', 'Art. 18', 'Financial entities must classify ICT-related incidents according to criteria including number of affected clients, duration, geographic spread, data losses.', 'Establish incident classification criteria aligned with DORA requirements.', 1),
    ('00000000-0000-0000-0002-000000000002', 'Can you report major ICT incidents to the competent authority?', 'Kas saate teatada olulistest IKT intsidentidest pädevale asutusele?', 'Art. 19', 'Major ICT-related incidents must be reported to the relevant competent authority using specified templates and timelines.', 'Set up reporting procedures and templates for major ICT incident notification.', 2),
    ('00000000-0000-0000-0002-000000000002', 'Do you maintain a log of all ICT-related incidents?', 'Kas peate kõigi IKT-ga seotud intsidentide logi?', 'Art. 17', 'Financial entities must record all ICT-related incidents and significant cyber threats with root cause analysis after resolution.', 'Implement a centralized incident logging and tracking system.', 3),
    ('00000000-0000-0000-0002-000000000002', 'Is there a defined timeline for incident notifications?', 'Kas intsidentide teavituste jaoks on määratud ajakava?', 'Art. 19', 'Initial notification must be submitted promptly, followed by intermediate and final reports within specified timeframes.', 'Define clear timelines for initial, intermediate and final incident reports.', 4),
    ('00000000-0000-0000-0002-000000000002', 'Do you analyze ICT incidents to identify root causes?', 'Kas analüüsite IKT intsidente algpõhjuste tuvastamiseks?', 'Art. 17', 'Post-incident reviews must identify root causes and establish measures to prevent recurrence.', 'Conduct thorough post-incident reviews with documented root cause analysis.', 5),
    ('00000000-0000-0000-0002-000000000002', 'Are clients informed about major ICT incidents affecting them?', 'Kas kliente teavitatakse neid mõjutavatest olulistest IKT intsidentidest?', 'Art. 19', 'When a major ICT incident impacts financial interests of clients, they should be informed about the incident and corrective measures taken.', 'Develop client communication templates and procedures for major incidents.', 6),
    ('00000000-0000-0000-0002-000000000002', 'Do you track cyber threats in addition to incidents?', 'Kas jälgite lisaks intsidentidele ka küberohtusid?', 'Art. 20', 'Financial entities may voluntarily notify the competent authority of significant cyber threats relevant to the financial system.', 'Implement cyber threat monitoring and voluntary reporting procedures.', 7),
    ('00000000-0000-0000-0002-000000000002', 'Is there communication planning for ICT crisis scenarios?', 'Kas IKT kriisistsenaariumide jaoks on kommunikatsiooniplaan?', 'Art. 14', 'Communication plans covering both internal escalation and external notification are required for crisis management.', 'Create comprehensive crisis communication plans covering all stakeholders.', 8);

-- Questions for Domain 3: Resilience Testing (8 questions)
INSERT INTO regulation_question (domain_id, question_en, question_et, article_ref, explanation_en, recommendation_en, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000003', 'Do you conduct regular vulnerability assessments?', 'Kas teete regulaarseid haavatavuse hindamisi?', 'Art. 25', 'Digital operational resilience testing programme must include vulnerability assessments, open source analyses, and network security assessments.', 'Schedule regular vulnerability scans and assessments of all critical systems.', 1),
    ('00000000-0000-0000-0002-000000000003', 'Is there a digital operational resilience testing programme?', 'Kas on olemas digitaalse tegevuskerksuse testimise programm?', 'Art. 24', 'Financial entities must establish, maintain and review a sound testing programme as integral part of the ICT risk management framework.', 'Develop a comprehensive testing programme covering all critical ICT systems.', 2),
    ('00000000-0000-0000-0002-000000000003', 'Do you perform scenario-based testing?', 'Kas teete stsenaariumipõhist testimist?', 'Art. 25', 'Testing must include scenario-based tests, compatibility testing, performance testing and end-to-end testing.', 'Design realistic scenarios including cyber attack simulations for testing.', 3),
    ('00000000-0000-0000-0002-000000000003', 'Are threat-led penetration tests conducted (if applicable)?', 'Kas tehakse ohuhinnangu-põhiseid läbistusteste (kui kohaldatav)?', 'Art. 26', 'Entities identified by competent authorities must carry out threat-led penetration testing (TLPT) at least every 3 years.', 'Engage qualified testers for TLPT covering critical live production systems.', 4),
    ('00000000-0000-0000-0002-000000000003', 'Are test results documented and remediated?', 'Kas testimise tulemused dokumenteeritakse ja parandatakse?', 'Art. 24', 'All testing findings must be documented with appropriate remediation actions and timelines.', 'Track all testing findings to resolution with management oversight.', 5),
    ('00000000-0000-0000-0002-000000000003', 'Do tests cover all critical ICT systems?', 'Kas testid hõlmavad kõiki kriitilisi IKT süsteeme?', 'Art. 24', 'Testing programme must cover all critical and important functions as part of the digital operational resilience framework.', 'Ensure testing scope includes all critical and important business functions.', 6),
    ('00000000-0000-0000-0002-000000000003', 'Are external testers used for independent assessments?', 'Kas kasutatakse sõltumatuteks hindamisteks väliseid testijaid?', 'Art. 26', 'External testers must be certified and possess relevant competence for TLPT exercises.', 'Engage reputable external security firms for independent testing and TLPT.', 7),
    ('00000000-0000-0000-0002-000000000003', 'Is source code review performed on critical applications?', 'Kas tehakse kriitiliste rakenduste lähtekoodi ülevaadet?', 'Art. 25', 'Source code reviews of in-house developed applications should form part of the testing programme.', 'Include source code security reviews in the software development lifecycle.', 8);

-- Questions for Domain 4: Third-Party Risk (10 questions)
INSERT INTO regulation_question (domain_id, question_en, question_et, article_ref, explanation_en, recommendation_en, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000004', 'Do you maintain a register of all ICT third-party providers?', 'Kas peate kõigi IKT kolmanda osapoole teenusepakkujate registrit?', 'Art. 28', 'Financial entities must maintain a register of information on all contractual arrangements with ICT third-party providers.', 'Create and maintain a comprehensive third-party provider register.', 1),
    ('00000000-0000-0000-0002-000000000004', 'Are ICT third-party risks included in the risk management framework?', 'Kas IKT kolmanda osapoole riskid on kaasatud riskijuhtimise raamistikku?', 'Art. 28', 'Management of ICT third-party risk shall be an integral part of the ICT risk management framework.', 'Integrate third-party risk management into the overall ICT risk framework.', 2),
    ('00000000-0000-0000-0002-000000000004', 'Do contracts with ICT providers include DORA-required clauses?', 'Kas IKT teenusepakkujate lepingud sisaldavad DORA nõutud klausleid?', 'Art. 30', 'Contractual arrangements must include service level descriptions, data location provisions, and audit rights.', 'Review and update all ICT provider contracts to include DORA-required provisions.', 3),
    ('00000000-0000-0000-0002-000000000004', 'Is due diligence performed before engaging ICT providers?', 'Kas enne IKT teenusepakkujate kaasamist tehakse hoolsuskontrolli?', 'Art. 28', 'Due diligence must be conducted on prospective ICT providers before entering into contractual arrangements.', 'Establish a due diligence process for evaluating new ICT third-party providers.', 4),
    ('00000000-0000-0000-0002-000000000004', 'Do you assess concentration risk for critical ICT services?', 'Kas hindate kriitiliste IKT teenuste kontsentratsiooniriski?', 'Art. 29', 'Financial entities must identify and assess concentration risks arising from ICT third-party dependencies.', 'Map critical dependencies and assess concentration risk across providers.', 5),
    ('00000000-0000-0000-0002-000000000004', 'Are exit strategies defined for critical ICT third-party services?', 'Kas kriitiliste IKT kolmanda osapoole teenuste jaoks on määratletud väljumisstrateegia?', 'Art. 28', 'Exit strategies must ensure transition without disruption to business activities or compliance obligations.', 'Develop documented exit strategies for all critical ICT service providers.', 6),
    ('00000000-0000-0000-0002-000000000004', 'Do you monitor ICT third-party provider performance?', 'Kas jälgite IKT kolmanda osapoole teenusepakkuja tulemuslikkust?', 'Art. 28', 'Ongoing monitoring of ICT third-party provider performance against SLAs is required.', 'Implement regular performance monitoring and review of ICT providers.', 7),
    ('00000000-0000-0000-0002-000000000004', 'Are sub-outsourcing arrangements monitored?', 'Kas allhankelepinguid jälgitakse?', 'Art. 29', 'Financial entities must manage risks arising from sub-outsourcing by ICT third-party providers.', 'Include sub-outsourcing monitoring and approval requirements in contracts.', 8),
    ('00000000-0000-0000-0002-000000000004', 'Is data location and processing jurisdiction documented?', 'Kas andmete asukoht ja töötlemise jurisdiktsioon on dokumenteeritud?', 'Art. 30', 'Contracts must specify the locations where data is processed and stored.', 'Document data processing locations and ensure compliance with jurisdiction requirements.', 9),
    ('00000000-0000-0000-0002-000000000004', 'Do you have audit rights over ICT third-party providers?', 'Kas teil on auditeerimisõigused IKT kolmanda osapoole teenusepakkujate üle?', 'Art. 30', 'Contractual arrangements must include provisions on unrestricted access and audit rights.', 'Ensure contracts include full audit and access rights with regular exercises.', 10);

-- Questions for Domain 5: Information Sharing (5 questions)
INSERT INTO regulation_question (domain_id, question_en, question_et, article_ref, explanation_en, recommendation_en, sort_order) VALUES
    ('00000000-0000-0000-0002-000000000005', 'Do you participate in cyber threat information sharing?', 'Kas osalete küberohu teabe jagamises?', 'Art. 45', 'Financial entities may exchange cyber threat information among themselves, including IoCs, tactics and techniques.', 'Join industry information sharing groups and establish sharing protocols.', 1),
    ('00000000-0000-0000-0002-000000000005', 'Are information sharing arrangements documented?', 'Kas teabe jagamise kokkulepped on dokumenteeritud?', 'Art. 45', 'Sharing arrangements must specify conditions for participation and handling of shared information.', 'Formalize information sharing arrangements with clear terms and conditions.', 2),
    ('00000000-0000-0000-0002-000000000005', 'Is shared information protected and handled appropriately?', 'Kas jagatud teavet kaitstakse ja käsitletakse asjakohaselt?', 'Art. 45', 'Shared information must be protected in terms of confidentiality and data protection requirements.', 'Implement controls for protecting shared cyber threat intelligence.', 3),
    ('00000000-0000-0000-0002-000000000005', 'Do you contribute to sector-wide resilience awareness?', 'Kas panustate sektoriülesesse kerksuse teadlikkusse?', 'Art. 45', 'Information sharing should enhance digital operational resilience of the financial sector as a whole.', 'Actively contribute threat intelligence to improve sector-wide resilience.', 4),
    ('00000000-0000-0000-0002-000000000005', 'Are sharing activities reported to competent authorities when required?', 'Kas jagamistegevustest teatatakse pädevatele asutustele vajadusel?', 'Art. 45', 'Financial entities must notify competent authorities of their participation in information sharing arrangements.', 'Report information sharing participation to the relevant competent authority.', 5);
